language: csharp

os: linux # Ubuntu 14.04
dist: trusty
sudo: required
dotnet: 2.0.0

services:
  - docker
  
script:
  - docker-compose up -d
  - docker-compose up -d
  - export kairos_url=$(docker inspect -f "{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}" kairosdbclientdotnet_dev-kairos-1_1)
  - dotnet restore
  - dotnet build
  - dotnet test test/KairosDbClient.IntegrationTests
  - "if [[ $TRAVIS_PULL_REQUEST == 'false' && $TRAVIS_TAG ]]; then
    dotnet pack src/KairosDbClient --configuration Release /p:Version=$TRAVIS_TAG;
    nuget push src/KairosDbClient/bin/Release/*.nupkg -ApiKey $NUGET_API_KEY;
    fi"
